# Generated by Django 5.0.7 on 2024-07-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('description', models.TextField()),
                ('isbn_13', models.CharField(max_length=13, unique=True)),
                ('page_count', models.IntegerField()),
                ('thumbnail_url', models.URLField(max_length=255)),
            ],
        ),
    ]
