# Generated by Django 5.0.7 on 2024-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_cart_transaction_detect_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='booked',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=10),
        ),
    ]
